export const RedirectMap: Record<string, string> = {
    '/log': '/developer/log',
    '/projects': '/developer/project',
    '/feedback': '/contact/feedback',
    '/debug': '',
    '/demo': '/developer/demo',
    '/trash': '/manage/trash',
    '/page': '/manage/page',
    '/light': '/manage/light',
    '/manage/pages': '/manage/page',
    '/setting': '/ext/setting',
    '/pagenote': '/ext/manage',
    '/signup': '/signin',
    '/me': '/pagenote',
    '/webpage': '/pagenote',
    '/post': '/sitemap',
    '/data': '/ext/setting#/data',
    '/backup': '/ext/setting#/data/backup',
    '/skills':'/question',
    '/install':'/download',
    '/help':'/question',
    '/pro-plan':'/vip',
}
