export default{
    SHARENAME:"easyshare",
    WAITING:"WAITING",

    INITCOMPELETE:"INITCOMPELETE",
    RECORDING:"RECORDING",
    PAUSE:"PAUSE",
    RECORDED:"RECORDED",
    FINNISHED:"FINNISHED",
    REPLAYING:"REPLAYING",
    REPLAYFINISHED:"REPLAYFINISHED"
}