name: build extension web

on:
  push:
    paths:
      - 'apps/web/**'
    branches:
      - main
      - dev
#      - 'feat*'
#    tags:
#      - 'v[0-9]+.[0-9]+.[0-9]+'

jobs:
  build:
    runs-on: ubuntu-latest
    environment: Production

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          fetch-tags: true

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18.x'


      - name: dependencies cache
        uses: actions/cache@v3
        with:
          path: |
            ~/.npm
            ~/.cache
            ~/node_modules
          key: ${{ runner.os }}-dependencies-${{ hashFiles('**/yarn.lock') }}
          restore-keys: ${{ runner.os }}-dependencies-

      - name: Yarn install
        run: yarn install


      - name: build ext-web
        run: |
          yarn run build:ext-web
          rm -rf apps/web/out/yml
          rm -rf apps/web/out/404.html
          rm -rf apps/web/out/ads.txt
          rm -rf apps/web/out/base_default_page_data.json
          rm -rf apps/web/out/changelog.json
          rm -rf apps/web/out/markdown.css
          rm -rf apps/web/out/markdown2.css
          rm -rf apps/web/out/robots.txt
          rm -rf apps/web/out/sitemap.xml
          rm -rf apps/web/out/sw.js
          rm -rf apps/web/out/version.json
          rm -rf apps/web/out/worker-register.js
          rm -rf apps/web/out/sw.resource.js

      - name: Upload build web Artifact
        uses: actions/upload-artifact@v3
        with:
          name: ext-web
          path: apps/web/out
          retention-days: 5


